title: NHGM.github.io
description: NHGM.github.io is for amateur programmers.
show_downloads: False
#google_analytics: G-EEDJNWDQYY
#theme: jekyll-theme-midnight
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
